### ISSUE TITLE
"Error occured Could not read device list from server! Error is: No value for widget"

### ISSUE THREAD

**Issue by tavalin** [schdef/homecompanion#14] opened 2016-01-06 23:19 UTC
I get this error message upon configuring the app to point at my openHAB2 setup.

Server is reachable so I've attached the JSON response from the REST API below.
```
{"name":"test","label":"Main Menu","link":"http://192.168.0.252:8080/rest/sitemaps/test","homepage":{"id":"main","title":"Main Menu","link":"http://192.168.0.252:8080/rest/sitemaps/main/main","leaf":false,"widgets":[{"widgetId":"main_0","type":"Frame","label":"Dashboard","icon":"frame","mappings":[],"widgets":[{"widgetId":"main_0_0","type":"Switch","label":"Morning Alarm Test","icon":"switch","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/morning_alarm","state":"NULL","type":"SwitchItem","name":"morning_alarm","label":"Morning Alarm Test","tags":[],"groupNames":[]},"widgets":[]},{"widgetId":"main_0_0_1","type":"Switch","label":"night_switch","icon":"switch","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/night_switch","state":"NULL","type":"SwitchItem","name":"night_switch","tags":[],"groupNames":[]},"widgets":[]},{"widgetId":"main_0_0_1_2","type":"Text","label":"Outside Temperature [6.0 Â°C]","icon":"temperature","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/Temperature","state":"6","stateDescription":{"pattern":"%.1f Â°C","readOnly":true,"options":[]},"type":"NumberItem","name":"Temperature","label":"Outside Temperature","category":"temperature","tags":[],"groupNames":[]},"widgets":[]}]},{"widgetId":"main_1","type":"Frame","label":"Lights","icon":"frame","mappings":[],"widgets":[{"widgetId":"main_1_0","type":"Switch","label":"All lights [(1)]","icon":"light","mappings":[{"command":"OFF","label":"All Off"}],"item":{"members":[],"link":"http://192.168.0.252:8080/rest/items/light_switches","state":"ON","stateDescription":{"pattern":"(%d)","readOnly":false,"options":[]},"type":"GroupItem","name":"light_switches","label":"All lights","category":"light","tags":[],"groupNames":[]},"widgets":[]},{"widgetId":"main_1_0_1","type":"Group","label":"All light controls","icon":"light","mappings":[],"item":{"members":[],"link":"http://192.168.0.252:8080/rest/items/light_controls","state":"UNDEF","type":"GroupItem","name":"light_controls","label":"All light controls","category":"light","tags":[],"groupNames":[]},"linkedPage":{"id":"0101","title":"All light controls","icon":"light","link":"http://192.168.0.252:8080/rest/sitemaps/main/0101","leaf":false,"widgets":[{"widgetId":"0101_0","type":"Group","label":"Bedroom light","icon":"light","mappings":[],"item":{"members":[],"link":"http://192.168.0.252:8080/rest/items/bedroom_light_controls","state":"UNDEF","type":"GroupItem","name":"bedroom_light_controls","label":"Bedroom light","category":"light","tags":[],"groupNames":["light_controls"]},"linkedPage":{"id":"bedroom_light_controls","title":"Bedroom light","icon":"light","link":"http://192.168.0.252:8080/rest/sitemaps/main/bedroom_light_controls","leaf":true,"widgets":[{"widgetId":"bedroom_light_controls_0","type":"Switch","label":"Switch","icon":"switch","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_light","state":"ON","type":"SwitchItem","name":"bedroom_light","label":"Switch","category":"switch","tags":[],"groupNames":["bedroom_light_controls","light_switches"]},"widgets":[]},{"widgetId":"bedroom_light_controls_1","type":"Slider","label":"Brightness","icon":"slider","mappings":[],"switchSupport":true,"sendFrequency":0,"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_light_brightness","state":"0","type":"DimmerItem","name":"bedroom_light_brightness","label":"Brightness","tags":[],"groupNames":["bedroom_light_controls"]},"widgets":[]},{"widgetId":"bedroom_light_controls_2","type":"Switch","label":"White mode","icon":"switch","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_light_white","state":"OFF","type":"SwitchItem","name":"bedroom_light_white","label":"White mode","category":"switch","tags":[],"groupNames":["bedroom_light_controls","light_switches"]},"widgets":[]},{"widgetId":"bedroom_light_controls_3","type":"Colorpicker","label":"Colour","icon":"slider","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_light_colour","state":"353,83,100","type":"ColorItem","name":"bedroom_light_colour","label":"Colour","category":"slider","tags":[],"groupNames":["bedroom_light_controls"]},"widgets":[]}]},"widgets":[]}]},"widgets":[]}]},{"widgetId":"main_2","type":"Frame","label":"Heating","icon":"frame","mappings":[],"widgets":[{"widgetId":"main_2_0","type":"Switch","label":"All heating [(1)]","icon":"heating","mappings":[{"command":"OFF","label":"All Off"}],"item":{"members":[],"link":"http://192.168.0.252:8080/rest/items/Heating","state":"ON","stateDescription":{"pattern":"(%d)","readOnly":false,"options":[]},"type":"GroupItem","name":"Heating","label":"All heating","category":"heating","tags":[],"groupNames":[]},"widgets":[]},{"widgetId":"main_2_0_1","type":"Group","label":"All heating [(1)]","icon":"heating","mappings":[],"item":{"members":[],"link":"http://192.168.0.252:8080/rest/items/Heating","state":"ON","stateDescription":{"pattern":"(%d)","readOnly":false,"options":[]},"type":"GroupItem","name":"Heating","label":"All heating","category":"heating","tags":[],"groupNames":[]},"linkedPage":{"id":"0201","title":"All heating [(1)]","icon":"heating","link":"http://192.168.0.252:8080/rest/sitemaps/main/0201","leaf":true,"widgets":[{"widgetId":"0201_0","type":"Switch","label":"Bedroom heating","icon":"heating","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_heating","state":"ON","type":"SwitchItem","name":"bedroom_heating","label":"Bedroom heating","category":"heating","tags":[],"groupNames":["Heating"]},"widgets":[]},{"widgetId":"0201_1","type":"Text","label":"Target temperature [21.0 Â°C]","icon":"heating","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_temp_target","state":"21","stateDescription":{"pattern":"%.1f Â°C","readOnly":false,"options":[]},"type":"NumberItem","name":"bedroom_temp_target","label":"Target temperature","category":"heating","tags":[],"groupNames":["Heating"]},"widgets":[]}]},"widgets":[]},{"widgetId":"main_2_0_1_2","type":"Setpoint","label":"Target temperature [21.0 Â°C]","icon":"heating","mappings":[],"minValue":15,"maxValue":25,"step":0.5,"item":{"link":"http://192.168.0.252:8080/rest/items/bedroom_temp_target","state":"21","stateDescription":{"pattern":"%.1f Â°C","readOnly":false,"options":[]},"type":"NumberItem","name":"bedroom_temp_target","label":"Target temperature","category":"heating","tags":[],"groupNames":["Heating"]},"widgets":[]}]},{"widgetId":"main_3","type":"Frame","label":"Test","icon":"frame","mappings":[],"widgets":[{"widgetId":"main_3_0","type":"Text","label":"Title [-]","icon":"text","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sq_test_title","state":"NULL","stateDescription":{"pattern":"%s","readOnly":false,"options":[]},"type":"StringItem","name":"sq_test_title","label":"Title","tags":[],"groupNames":[]},"widgets":[]},{"widgetId":"main_3_0_1","type":"Switch","label":"Squeeze test switch","icon":"switch","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sq_test_switch","state":"NULL","type":"SwitchItem","name":"sq_test_switch","label":"Squeeze test switch","tags":[],"groupNames":[]},"widgets":[]},{"widgetId":"main_3_0_1_2","type":"Switch","label":"test_switch","icon":"switch","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/test_switch","state":"NULL","type":"SwitchItem","name":"test_switch","tags":[],"groupNames":[]},"widgets":[]}]},{"widgetId":"main_4","type":"Frame","label":"Sensors","icon":"frame","mappings":[],"widgets":[{"widgetId":"main_4_0","type":"Group","label":"Aeotec Multisensor 6 (Bedroom)","icon":"group","mappings":[],"item":{"members":[],"link":"http://192.168.0.252:8080/rest/items/MultiSensor","state":"UNDEF","type":"GroupItem","name":"MultiSensor","label":"Aeotec Multisensor 6 (Bedroom)","tags":[],"groupNames":[]},"linkedPage":{"id":"0400","title":"Aeotec Multisensor 6 (Bedroom)","icon":"group","link":"http://192.168.0.252:8080/rest/sitemaps/main/0400","leaf":true,"widgets":[{"widgetId":"0400_0","type":"Text","label":"Last updated [Wed 23:16:20]","icon":"clock","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_last_update","state":"2016-01-06T23:16:20","stateDescription":{"pattern":"%1$ta %1$tT","readOnly":false,"options":[]},"type":"DateTimeItem","name":"sensor_1_last_update","label":"Last updated","category":"clock","tags":[],"groupNames":["MultiSensor"]},"widgets":[]},{"widgetId":"0400_1","type":"Text","label":"Temperature: [22.7 Â°C]","icon":"temperature","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_temp","state":"22.7","stateDescription":{"pattern":"%.1f Â°C","readOnly":false,"options":[]},"type":"NumberItem","name":"sensor_1_temp","label":"Temperature:","category":"temperature","tags":[],"groupNames":["MultiSensor","MultiSensor_Sensors"]},"widgets":[]},{"widgetId":"0400_2","type":"Text","label":"Luminance: [0 Lux]","icon":"sun","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_luminance","state":"0","stateDescription":{"pattern":"%.0f Lux","readOnly":false,"options":[]},"type":"NumberItem","name":"sensor_1_luminance","label":"Luminance:","category":"sun","tags":[],"groupNames":["MultiSensor","MultiSensor_Sensors"]},"widgets":[]},{"widgetId":"0400_3","type":"Text","label":"Humidity: [44 %]","icon":"humidity","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_humidity","state":"44","stateDescription":{"pattern":"%.0f %%","readOnly":false,"options":[]},"type":"NumberItem","name":"sensor_1_humidity","label":"Humidity:","category":"humidity","tags":[],"groupNames":["MultiSensor","MultiSensor_Sensors"]},"widgets":[]},{"widgetId":"0400_4","type":"Text","label":"UV: [0 %]","icon":"sun","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_uv","state":"0","stateDescription":{"pattern":"%.0f %%","readOnly":false,"options":[]},"type":"NumberItem","name":"sensor_1_uv","label":"UV:","category":"sun","tags":[],"groupNames":["MultiSensor","MultiSensor_Sensors"]},"widgets":[]},{"widgetId":"0400_5","type":"Text","label":"Movement: [Motion]","icon":"present","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_motion","state":"Motion","stateDescription":{"pattern":"","readOnly":false,"options":[]},"type":"ContactItem","name":"sensor_1_motion","label":"Movement:","category":"present","tags":[],"groupNames":["MultiSensor","MultiSensor_Sensors"]},"widgets":[]},{"widgetId":"0400_6","type":"Text","label":"Battery [50 %]","icon":"battery","mappings":[],"item":{"link":"http://192.168.0.252:8080/rest/items/sensor_1_battery","state":"50","stateDescription":{"pattern":"%s %%","readOnly":false,"options":[]},"type":"NumberItem","name":"sensor_1_battery","label":"Battery","category":"battery","tags":[],"groupNames":["MultiSensor","MultiSensor_Sensors"]},"widgets":[]}]},"widgets":[]}]}]}}
```

**Comment by schdef** [comment] 2016-01-15 19:46
Going to write a unit test to reproduce the error.

**Comment by schdef** [comment] 2016-01-19 07:44
Okay some changes to read successful your JSON file are done. Because I don't have yet an openHAB2 running, can you test it?

**Comment by Tavalin** [comment] 2016-01-26 17:34
Thanks for your time on this.

The JSON is read correctly (I think - I can see items on the watch and phone UI) but the UX doesn't seem to work.  When I clicked on a light the (real) light did not change...I'm not sure if "TOGGLE" is a real OH2 command.

**Comment by schdef** [comment] 2016-01-26 19:56
Do you have any idea how the command looks like?

**Comment by Tavalin** [comment] 2016-01-28 21:30
I've had another look at this, how are you sending the commands to openHAB? The REST API has changed in OH2.

**Comment by schdef** [comment] 2016-01-30 13:19
Oh okay. I'll close this bug and create another one to fix switching devices for openHAB2.

**Closed by schdef** 2016-01-30 13:19 UTC
Labels: bug, enhancement
